export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const READ_POST_REQUEST = "READ_POST_REQUEST";
export const READ_POST_SUCCESS = "READ_POST_SUCCESS";
export const READ_POST_FAILURE = "READ_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

// export const ActionTypes = {
//   FETCH_POST_REQUEST: "FETCH_POST_REQUEST",
//   FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
//   FETCH_POST_FAILURE: "FETCH_POST_FAILURE",

//   CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
//   CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
//   CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

//   READ_POST_REQUEST: "READ_POST_REQUEST",
//   READ_POST_SUCCESS: "READ_POST_SUCCESS",
//   READ_POST_FAILURE: "READ_POST_FAILURE",

//   UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
//   UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
//   UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",

//   DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
//   DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
//   DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
// };
